Motion-Project/motion

configure.ac
motion-dist.conf.in
motion.c
netcam_rtsp.c
track.c
video.h
video2.c

This adds support to motion for OpenBSD's implementation of V4L2, works fine with a USB webcam using the uvideo(4) driver.

OpenBSD V4L2 support

---

conf.c
motion-dist.conf.in
motion.1

Fix typo. EMR is not a valid log level. Should be EMG

Fix typo. EMR is not a valid log level. Should be EMG

---

track.c

track.c compiles with errors if omitted,

V4L2 missing a #include videodev2.h

---

event.c
ffmpeg.c
ffmpeg.h

The current definitions (char codec_swf[3] = "swf" etc) are declared
one character too short resulting in stack corruption or crashes in
some cases.
To avoid the possibility of an error at all, we change ffmpeg_open to
take a const char * as it doesn't need to alter the string.
Closes https://github.com/Mr-Dave/motion/issues/109

Fix stack corruption in event_ffmpeg_timelapse

---

CHANGELOG
configure.ac

This is a slight revision to the original.  The check for the pkg-config needed to be moved above the check for the ffmpeg.  This allows for the specification of the --without-ffmpeg option.  The original had the check for the pkg-config inside the IF condition.  Next, a ELSE clause was added to stop the configuration when users did not specify the --without-ffmpeg option and the required libraries are not found.

Pkg config

---

configure.ac

Currently if users run autoreconf then configure without having
pkg-config installed, they see:
./configure: line 5283: syntax error near unexpected token FFMPEG,'
./configure: line 5283:    PKG_CHECK_MODULES(FFMPEG, libavutil
libavformat libavcodec libswscale, HAVE_FFMPEG=yes)'
This is not hugely helpful and causes support queries and confusion.
It is because the pkg.m4 file that defines PKG_CHECK_MODULES is not
available of pkg-config is not installed.
To work around this, remove PKG_CHECK_MODULES and do roughly the
equivalent calling pkg-config directly. To mirror the current
behaviour, we also add a test for pkg-config being present and abort
if it is not. (I am not 100% sure this is the desired behaviour, but
regardless this commit is still an improvement on what we currently
have.)

Produce more helpful error if pkg-config not installed

---

webhttpd.c

The weird </a/n> tag in the html was presumably meant to be a </a> followed by a new line.

Fix bad html in server home page

---

CHANGELOG
event.c
ffmpeg.c
ffmpeg.h
motion-dist.conf.in
motion.1
motion_guide.html
netcam.c
netcam_rtsp.c
netcam_rtsp.h

These commits address multiple issues with the ffmpeg processing.  
1. The variable bit rate parameter will control quality for all the codec/container options and will close #113.  
2. The presentation time stamps (pts) were not being set right for all the different containers which closes #56 and #132.  
3. Fixed the truncated images which closes #131.  
4. The ogg container was not able to be successfully implemented and was removed as a available option.  Specification of this container will result in Motion falling back to the default.   
5. Revisions have been included to handle the ffmpeg 3.0 changes and remove the depreciation warnings.  Closes #136 
6. The swf container for the timelapse needed to be changed to mpg.  Using a codec of mpeg2 with a swf container is not permitted. …

ffmpeg fixes

---

ffmpeg.c

I wanted to be able to configure the movie quality when using the h264 codec. This sets the "crf" option according to the ffmpeg_variable_bitrate option.

h264 codec: set crf option based on configured vbr

---

conf.c
event.c
logger.c
motion.c
motion.h
picture.c

This pull request will close #102 
This commit reverts  back the change in 3.2.12 which implemented setvbuf and user defined file buffers to increase the throughput of writing the jpgs.  The implementation used a set of 32 global buffers that do not appear to be thread safe.  The implementation also did not reinitialize the buffers after use which could be a issue.  
Further analysis and profiling is required to determine whether the throughput remains a issue and whether it needs to be addressed by a future change.

Revert to standard os file buffering

---

event.c
ffmpeg.c

I missed this in the previous changes.  The pts is now using timestamps to handle variable fps sources which will not work for time lapse.  This changes the pts  back to the default and assigns the fps to the user specified amount.

Timelapse fps and regression fixes

---

.travis.yml
ffmpeg.c
ffmpeg.h

I've tested this with the debian stable libavutil, plus the older one on travis, both work fine.
The travis config means we can setup travis to check that pull requests compile - I'll do that once this pull request is merged.

Fix for older libavutil + add travis configuration

---

ffmpeg.c
ffmpeg.h
netcam_rtsp.c
netcam_rtsp.h

I've resurrected the pull request that I'd previously closed here:
https://github.com/Motion-Project/motion/pull/149
I think the way we have the code on the current master may not match with the original intention of whoever wrote the code (though it is always hard to tell). Given that the functions aren't called from outside their .c files and weren't originally in the .h files I think it's reasonable to surmise that they were intended to be local to the .c files, so make them so. (Keeping functions only exposed the minimum amount necessary aids in figuring out how the rest of the code calls into a particular piece of code.)

Make some internal functions "static"

---

Makefile.in
conf.c
conf.h
configure.ac
mmalcam.c
mmalcam.h
motion-dist.conf.in
motion.h
raspicam/README.txt
raspicam/RaspiCLI.c
raspicam/RaspiCLI.h
raspicam/RaspiCamControl.c
raspicam/RaspiCamControl.h
video_common.c

Originally by dozencrows on github; mostly this commit:
https://github.com/dozencrows/motion/commit/6d1ed5bd011d83b6358daf86a20c60cb50d0418c
Changes to merge back into motion upstream made by Joseph Heenan (with
help from lowflyerUK on github, see https://github.com/dozencrows/motion/pull/1 ):
- changed back to using autoconf etc as per the main project
- submitted the one change we need to the raspicam files back upstream
( https://github.com/raspberrypi/userland/pull/332 )
- imported latest versions of files in raspicam, now exactly match upstream
- added README.txt to raspicam directory with brief explanation
- replaced some tabs with spaces
- removed dependency on checkout of raspberrypi userland repo; now we
use the headers provided by libraspberrypi-dev
- merged in a couple of the …

Initial support for MMAL camera on raspberry pi

---

Makefile.in

make clean currently removes all jpgs, which means it deletes the jpgs
used in the documentation (outputnormal1.jpg etc). This seems like it
wasn't intended.
I can't figure out why it deletes jpgs at all, it seems to date back
to the initial import of version 3.2.5 into svn in 2005 - seems safe
to remove it.

Stop "make clean" deleting documentation jpgs

---

conf.c

The while loop was missing a condition to stop at the start of the line,
so we'd carry on beyond the start of the buffer.
Closes #88

Fix for whitespace only lines in config file

---

conf.c
conf.h
configure.ac
motion.c
netcam.c
netcam_rtsp.c
stream.c
webhttpd.c

I've been finding this really useful; it gives me a meaningful way to remember which camera is which in the web configuration interface and also makes it really easy to find the right thread for a camera in gdb (the camera name shows up in "info threads"). I've fixed a couple of minor issues since this was last commented on and renamed the option to camera_name as that seems a better name (and is consistent with the camera_id integer settings that's been suggested in another pull request).
Based on a commit originally by Chris Roberts <86montecarlo@gmail.com>
camera_name allows naming of threads, is displayed in the motion control
webpage, and a new specifier (%$) added enabling it to be used for
filenames and such.
The changes I have made since Chris's commit:
1. Change format specifier …

Add camera_name setting to allow each camera to be given a name

---

motion.c

As per http://dev.mysql.com/doc/refman/5.7/en/mysql-library-init.html
we should init the mysql library before starting any threads, as
otherwise mysql_init is not thread safe.
Closes #103

Possible fix for failure to connect to mysql on startup

---

ffmpeg.c
ffmpeg.h

Revise the condition used for testing older versions of ffmpeg to use the AVFormat version number instead of the FF_API_PIX_FMT.  Closes #165

MYPixelFormat Revision

---

vloopback_motion.c

This closes #142 of compiler warnings on unused variables.

Remove unused variables in vloopback_motion

---

ffmpeg.c

When rtsp cameras lose connection, avcodec reports a error on each attempt to reconnect which floods the logs.  This change suppresses these messages.  In addition, it sends to the motion debug log messages regarding the UE golob.  This is a message from some cameras that is not able to be fixed since it is the firmware of the camera that is sending incorrect data.
Closes #159

Suppress some messages from avcodec

---

configure.ac

Do not only check for static libjpeg.a but also for dynamic libjpeg.so
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>

Fix jpeg-turbo detection

---

.travis.yml

Duplicated the addons section of travis so that I could add in the sourceline to apt for 14.04 so ffmpeg can be installed from the PPA (https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media)
You can see the complete build output here: https://travis-ci.org/mterzo/motion/builds/160351676
12.04 lib versions:
```
$ avplay -version
avplay version 0.8.17-4:0.8.17-0ubuntu0.12.04.2, Copyright (c) 2003-2014 the Libav developers
built on Apr  1 2016 14:24:20 with gcc 4.6.3
avplay 0.8.17-4:0.8.17-0ubuntu0.12.04.2
libavutil    51. 22. 3 / 51. 22. 3
libavcodec   53. 35. 0 / 53. 35. 0
libavformat  53. 21. 1 / 53. 21. 1
libavdevice  53.  2. 0 / 53.  2. 0
libavfilter   2. 15. 0 /  2. 15. 0
libswscale    2.  1. 0 /  2.  1. 0
libpostproc  52.  0. 0 / 52.  0. 0
```
14.04 lib versions:
```
avplay …
```

Adding ubuntu 14.04 to build along with 12.04 in travis-ci

---

configure.ac

Replace usage of AC_CHECK_FILE by test -f to check the existence of
sqlite3.c as AC_CHECK_FILE does not work when cross-compiling
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>

Fix detection of sqlite3 when cross-compiling

---

configure.ac

When jpeg-turbo was enabled, LIBS was uncorrectly set: -lpthread, -lm,
... was lost. Same issue with CFLAGS.
Fixes #17.
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>

Fix LIBS and CFLAGS when jpeg-turbo is enabled

---

configure.ac

With this modification, the user will be able to specify the path to
sdl-config which can be outside his path (for example on embedded
buildsystem such as buildroot)
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>

Change --without-sdl to --with-sdl=[DIR]

---

motion_guide.html
picture.c

While trying to add mask support to motionEye, I found out that the mask file image must match that of the captured image.
This is acceptable for local V4L(2) cameras whose resolution is normally explicitly specified using `width` and `height` directives. But when it comes to (M)JPEG netcams, where **the image size is not known beforehand**, it makes it impossible for a frontend to **automatically generate a suitable mask** (which is what I'm trying to achieve with motionEye these days).
I thought that resizing the PGM mask file as soon as it is requested and loaded is the easiest solution to my problem and the best thing to do in general, when sizes don't match. This pull request implements a very simple resize method applied on the PGM mask file when required.

automatically resize mask image if size differs from that of the captured image

---

motion-dist.conf.in
motion_guide.html

Guys, what do you think about extending examples of `extpipe`? The existing one may be too scary for users, so I have added few more. They are simple and use different encoders to better demonstrate the approach.
```
Updated extpipe examples with ultrafast H264 (ffmpeg, mencoder and x264)
Also updated previous example to use %w and %h variables
```

Updated extpipe examples with ultrafast H264 (ffmpeg, mencoder and x264)

---

webhttpd.c

When the web control is accessed via a IPv6 address, e.g. `http://[::1]:8080/`, the links displayed in the web control page were incorrect. This is because the hostname function simply looked for the first colon in the address, and cut off everything after that, assuming that that is the port number.
This checks if the hostname starts with an `[`, meaning it is an IPv6 address (according to [RFC 3986#3.2.2](https://tools.ietf.org/html/rfc3986#section-3.2.2)), and properly finds the colon after the closing `]`.

Fix hostname determination for IPv6 addresses in web server.

---

configure.ac

As documented in issue #169, the recently added MMAL camera support for the
Raspberry Pi does not build on the Wheezy version of Raspbian.
This option disables the autoconf generation of MMAL dependencies.

Adds --without-mmal option to configure.

---

stream.c
webhttpd.c

Clean up HTML:
* Use the HTML5 doctype everywhere, as [recommended](https://www.w3.org/QA/Tips/Doctype) by the W3C. This shouldn't have any effect right now, but is good to have if we want more complex HTML in the future.
* Use lowercase HTML tags (more readable)
* Line breaks with `\n` instead of `\r\n` (`\r\n` is only needed in HTTP headers)
* Line breaks in more logical places in the HTML.

Cleanup HTML.

---

webhttpd.c

In common with other recent changes, remove another place where
"Thread" is visible to the user.
We also now use the camera_id rather than the thread number. The
camera_id already defaults to the thread number, so this change
won't cause any difference for older config files that don't set
camera_id.

Replace "Thread x" with "Camera x" in the web ui

---

conf.c
conf.h
motion-dist.conf.in
motion.1
motion.c
motion_guide.html
stream.c
webhttpd.c

Remove option ipv6_enabled (IPv6 is always enabled)
Add option localhost_ipv4 (the user must choose to listen to IPv4 and IPv6 localhost, only relevant when the localhost option is set to on)
See #97 for more information

Rewrite sockets to be much simpler and properly support IPv6.

---

conf.c

The help comment didn't contain the necessary #s at the beginning.
Fixes #200

Fix for crash accessing camera_id / corrupt config files

---

stream.c

I accidentally introduced this bug in #197. When binding/listening to a socket fails, we do not close the socket. This could keep the socket occupied. After restarting motion, it can not bind on the same socket. `SO_REUSEADDR` will make sure we reuse any open socket, if it is there.

Reuse socket when still open, properly close on error

---

Makefile.in
README.FreeBSD
ffmpeg.h

* FreeBSD's `sed` is not compatible with our syntax. The change I made should also work fine on Linux.
* Add missing include.
* Update readme.
I have not tested it with actual webcams, but it compiles and runs fine.

Fix FreeBSD build

---

Makefile.in

The bsd compile pull revised the sed option to use -i.bak but this leaves behind bak files.  This alternative was found that was indicated to also be compatible without leaving bak files.

Alternative sed option to not create bak files

---

conf.c
motion-dist.conf.in
stream.c

`enable_ipv6 off` now (again) turns off IPv6 entirely.
I have set the default to `enable_ipv6 on`, since disabling it should only be necessary on a small set of systems.
Fixes #217

Put back option to disable IPv6

---

configure.ac
rotate.c

When trying to build motion in C11 (`-std=gnu11`) mode, it failed on the `rotate.c` file.
I fixed it by replacing our `swap_bytes` function by the system (glibc/FreeBSD) function, and the `__uint32` type by the C99 `uint32_t` type.
This requires presence of the `stdint.h` header, which should be available on any C99 compiler, and `byteswap.h`, which is available on any GNU/Linux system, or `sys/endian.h`, which has been available in FreeBSD for a long time.
Tested on FreeBSD 11 and Arch Linux x86_64.

Use system-provided bswap and uint32_t

---

motion_guide.html

This fixes a few misspelled words in `motion_guide.html`. It also specifies that `width` and `height` must be modulo 8 numbers.

motion_guide.html: minor typo fixes and updates

---

CMakeLists.txt
config.h.in
configure.ac
motion.h
pwc-ioctl.h
video.h
video2.c
video_freebsd.h

Should be pretty self-explanatory, with maybe one exception:
`MOTION_V4L2_OLD` was only used to do `#include <linux/time.h>` and  `#include <linux/videodev2.h>`.
* `time.h` is already correctly included in `motion.h`, which is included at the top of `video2.c`
* I moved `#include <linux/videodev2.h>` together with the other video headers in `video.h`

Cleanup old defines, FreeBSD CMake fix

---

conf.c
conf.h
logger.c
motion.c
motion.h
netcam_rtsp.c
pwc-ioctl.h
rotate.c

Note that the `#define BSD` is not needed, because `BSD` is already set in `<sys/param.h>`. See e.g. [here](http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system).
Verified compilation on FreeBSD, OpenBSD and macOS. NetBSD should also work although I couldn't get that working in a virtual machine.
Also, `context.tuner_dev` was never used, so I've removed that.

Fix OpenBSD and NetBSD compilation

---

motion.c

Previously the post_captured images were only saved when using
ffmpeg_output or use_extpipe. This changes the behavior to always save
them when post_capture is > 0.

Always save post_capture images

---

netcam.c

Simplify netcam connection setup, like in getaddrinfo manpage [example](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html).
Tested on Linux and FreeBSD. (update: also tested on macOS)
Should fix #285

Fix netcam getaddrinfo/connect usage

---

conf.c
conf.h
event.c
event.h
motion-dist.conf.in
motion.1
motion.c
motion_guide.html

This adds the event "ON_CAMERA_FOUND" for when a proper image is re-acquired after a camera has been lost. The place to call this event was already commented in 'motion.c', without an actual call or event to call.
The code is essentially a copy of 'on_camera_lost' and therefore is placed just after it in each file.
I've only briefly tested this with my setup of 5 net-cams and a notification script for lost/found. After disconnecting one camera, I received the 'lost notification' after motion detected it was gone. Quite quickly after re-connecting the camera, I received the 'found notification' as expected. No adverse side-effects were noted during the test.
I've updated the motion_guide.html and motion-dist.conf.in with this additon but have not modified the CHANGELOG.

Add in a 'on_camera_found' event

---

motion.c
motion_guide.html

This is a first draft of the proposed change related to issue #299.
Tested by streaming a grey image with various "text_left" variants.

Initial support for conversion specifier words

---

motion.service.in

The systemd service file, with `Type=simple`, expects motion to run in non-daemon mode, and not fork. If `daemon on` is set in `motion.conf`, the service will fail to run. Better to force the right mode from the service file to prevent misconfiguration.

Force motion to run in non-daemon mode in systemd service

---

motion.1
motion.c
motion_guide.html
picture.c

This PR fixes a issue with the previous implementation of the privacy mask. In the previous implementation, the mask was only applied to the y color space. This allowed for changes to still be seen with the Cr and Cb color spaces. This PR implements the mask in all the color spaces to completely mask the area and revises the masked space to be black.

Privacy Mask

---

.travis.yml
INSTALL
README.FreeBSD
README.MacOSX
configure.ac
motion_guide.html

The webp image format option is not available on older distributions
This commit revises the default for the webp to OFF.  Once the older
distributions reach EOL, the default can be changed back to ON.

Webp Default to Off

---

event.c

This caused memory access violation and process crash
Fixes https://github.com/Motion-Project/motion/issues/329

Bugfix: wrong variable logged when extpipe is already closed

---

event.c
ffmpeg.c
ffmpeg.h
motion.c
netcam_rtsp.c

The ffmpeg versions after 3.1 eliminated the stream codec which was used
in many different ways in the previous code.  This commit revises the ffmpeg
module to use smaller functions and eliminates the greyscale image handling
since all images are yuv.

ffmpeg 3.1 Revisions

---

.travis.yml
configure.ac
ffmpeg.c
ffmpeg.h
motion.1
motion_guide.html
netcam.c
netcam_rtsp.c

This commit adds functionality to use a v4l2 device via the netcam_url
option.  This will allow for more v4l2 devices since the netcam_url
uses the ffmpeg libraries which should be able to to decode and transform
the unusual pixel formats and sizes.
Closes #86 
Closes #92 
Closes #279

V4l2 via netcam

---

motion.c
motion.h

This is the code change described in #340 with some minor modifications (the additional mask is allocated with minimal size, i.e. only the size needed for the U & V sections of the image).
I tested this on one privacy mask with one (analog) camera at home, i.e. use with caution..

Improved privacy mask performances

---

CMakeLists.txt

Add libavdevice dependency, in consistency with autotools
This fixes #342

Fix cmake build on osx

---

conf.c
motion_guide.html

This fixes the comment for ffmpeg_variable_bitrate in 'config_params', which is used to write out the config file from the webui. Comment now matches the default config file. Reference issue #362.
Also noticed a missed change in the guide for 'netcam_http' to 'netcam_keepalive'.

Two small config and guide fixes

---

netcam.c
netcam_rtsp.c
netcam_rtsp.h

Related to issue #233.
* Use a dedicated `active` flag to tell if a `netcam->rtsp` context is connected and running, rather than checking (`netcam->rtsp->format_context != NULL`), because the latter may be true without a working connection. (There may be a better name for this flag than "active.")
* `netcam_open_codec()` and `netcam_rtsp_open_context()` should not return 0 if something is wrong
* Pass a `netcam` context into `netcam_interrupt_rtsp()` instead of `netcam->rtsp` so that the callback can check `netcam->finish` and react appropriately to the shutdown signal

Various fixes for RTSP crashes and/or Valgrind errors

---

CMakeLists.txt

Added libraries, include directories and extra source files to
enable a succesfull cross-compile with CMake.
Signed-off-by: Olivier Schonken <olivier.schonken@gmail.com>

Fix CMake building of MMAL driver for RaspberryPi

---

motion.h
netcam_rtsp.c

* Added `<assert.h>` to motion.h, so we can do assertions
* Changed the return-code semantics of `rtsp_decode_video()` and `rtsp_decode_packet()` to a tristate: negative on error, zero if no output is currently available, positive if output was successfully obtained
* Assert that `avcodec_send_packet()` never returns `AVERROR(EAGAIN)` (i.e. we never overfill the codec with packets)
* Treat `AVERROR(EAGAIN)` from `avcodec_receive_frame()` as a no-output, non-error condition (it means we need to send more packets before we can get a frame)
* Changed `netcam_read_rtsp_image()` to handle the case where the codec has a frame ready for output without needing any new packets
* Simplified the logic in the `netcam_read_rtsp_image()` packet-read loop
* Improved wording of some log messages
* …

Various fixes to Motion's interaction with FFmpeg vis-a-vis RTSP

---

configure.ac

Currently if "x${DISTRO}" isn't set to "Linux", unsafe header/library
path for cross-compilation such as '-I/usr/local/include' are used.
As a result, motion can't be cross-compiled, so change "x${DISTRO}" to
"${DISTRO}" as it seems that this was the intended use.
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Fix cross-compilation

---

configure.ac

Currently if the user sets --without-webp, WEBP is set to yes as
AC_ARG_WITH defines that its third argument is "action-if-present" so
use $withval to retrieve the value instead of always setting WEBP to yes
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Fix --without-webp

---

video_v4l2.c

I was running Motion 4.0.1 on FreeBSD 10.3-STABLE amd64. After connecting a webcam (Logitech C920). the console gives a continues stream of messages like this:
May 26 13:42:11 aurora kernel: WARNING pid 40273 (motion): ioctl sign-extension ioctl ffffffffc058560f
May 26 13:42:11 aurora kernel: WARNING pid 40273 (motion): ioctl sign-extension ioctl ffffffffc0585611
May 26 13:42:11 aurora kernel: WARNING pid 40273 (motion): ioctl sign-extension ioctl ffffffffc058560f
May 26 13:42:11 aurora kernel: WARNING pid 40273 (motion): ioctl sign-extension ioctl ffffffffc0585611
... etc.
This patch fixes that by making sure that the ioct() call gets a proper unsigned long request parameter.

Fix ioctl sign-extension warning on FreeBSD

---

INSTALL

Added libavdevice-dev to the list of dependencies.. because it was not listed in this docfile, but while ./configure it throws error message like:
"configure: error: Required ffmpeg packages 'libavutil-dev libavformat-dev libavcodec-dev libswscale-dev libavdevice-dev' were not found."

Updating INSTALL information

---

motion.c

This fixes an array overrun reported in #365. Also added an assertion to check the spot where the overrun occurred.

Reset image-ring cursors to zero on image-ring resize; fixes #365

---

configure.ac
logger.c
motion.h
netcam_rtsp.c

pthread_setname_np is a nonstandard GNU extension so put back its
detection, deleted by commit ab5835d43595ffc6e3b88b2ea5e4cd87a8c53e14,
to be able to cross-compile motion with non glibc toolchains
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Put back the detection of pthread_setname_np

---

event.c
ffmpeg.c
ffmpeg.h
motion.c

We eliminate gaps in movie (motion-->no_motion-->motion) by resetting movie start time. By doing so, we unintentionally reset the PTS value that has to be monotonically increasing, which triggers the error handling code that forces PTS to increment by 1 time unit per frame. The effect is a lot of frames are encoded into a short duration of few seconds, i.e. fast playback.
This PR does two things:
- Change last_pts to store pts_interval (in micro-seconds) instead of packet PTS (in stream time base unit). This allows us to store last_pts into base_pts in micro-seconds time base so it can be manipulated later.
- When we reset the movie start_time, we store last_pts into base_pts plus 1 frame duration, because it takes at least 1 frame to change cnt->detecting_motion state. In effect, this …

Fix movie gap elimination setting incorrect PTS

---

event.c
ffmpeg.c

1.  Revise the PTS to allow for the capture of the first image by revising the initialization of last_pts
2.  Elminate the incrementing by 1 when we have timing issues since this puts all subsequent
frames out of sync with timing/pts problems
3.  Unref the packets when encode and PTS functions return errors to prevent leaks.
4.  Revise logging to report more values when in test mode.

Additional PTS Changes

---

webhttpd.c

using "viewport" to solve that. see:
#381
#437
i just insert one line:
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=yes\">"
my first pullrequest...
2 screenshots. 1st small text. 2nd with "viewport"

On mobiles text inside the WEB UI is to small.

---

event.c

Fix close all file descriptors off by 1 error.
According to documentation, getdtablesize() returns the maximum number of files a process can have open, one more than the largest possible value for a file descriptor.
That means we close file descriptors starting from getdtablesize() - 1.

fix close all fds off by one error

---

ffmpeg.c

All PTS values are int64_t type, but on 32-bit machines, %d is 32-bits, so we end up printing the wrong values.
This PR changes %d to a more cross-platform friendly but ugly C99 macro PRId64.

fix logging of int64 PTS values

---

jpegutils.c
jpegutils.h
video_common.c

This pull request rewrites jpegutils.c to use the library functionality for providing a YCbCr format rather than trying to obtain raw conversions and do the down sampling ourselves.  
The previous module had three exposed functions for decode, decode_grey and encode.  The only function actually used by Motion was the decode so this is the only one included in the rewrite.
The new functionality included follows that used by netcam_jpeg.c and in the future the functionality between these modules should be consolidated.  For this PR the existing calling structure is maintained whereby the decode function in jpegutils.c is only called from the vid_mjpegtoyuv420 function.

Rewrite jpegutils.c

---

configure.ac

This allows flexible configuration of MMAL paths, which is useful for buildroot builds.

Allow configuration of include and lib paths for MMAL.

---

event.c

See https://github.com/Motion-Project/motion/issues/360#issuecomment-320937660
This is a fix to unblock users who wants to use latest version
Further discussion is needed to make a standard for file names

Fix for file names that contain "/" and non existing subdirs

---

netcam.c

If the boundary is not found for http streaming netcams in the header report and return error code.
Closes #389

Netcam Boundary

---

webhttpd.c

This covers one issue from #442, Web Control showing the wrong count of cameras.
Currently it just shows the count of cameras as the count of threads, which is only correct when running one camera with a single `motion.conf` file. Once you have a separate `camera1.conf` and so on, the thread count will always be one higher than the camera count.
In a similar manner, the stream preview section can duplicate a preview when motion is mis-configured with multiple cameras. If you leave `stream_port` enabled in `motion.conf` and use the same port in one of the camera files, it will show that preview twice.
The fixes for both are quite non-invasive and provide a cosmetic improvement.

Cosmetic fixes to the Web Control

---

.travis.yml
conf.c
configure.ac
jpegutils.c
motion.c
rotate.c

1.  Revise the developer warnings to treat all warnings as errors
2.  Revise a few of the comparisons of signed to unsigned.
3.  Isolate the setjmp to separate function since it is warning on 14.04
4.  Remove redundant clang OSX test since gcc is really clang according to travis logs

Resolve Developer Warnings

---

.travis.yml
configure.ac
test_builds.sh

This commit includes the following revisions to the testing.
1.  Add a output from the configure script to indicate version of libavformat.
2.  Add test_builds.sh script which includes tests for following with/without options.
--with-developer-flags, --without-ffmpeg, --without-mysql, --without-pgsql
--without-v4l2, --without-mysqlite3
3.  Add testing via docker for 16.04 and 17.04

Additional Travis Tests

---

ffmpeg.c
ffmpeg.h

This pull-request extends the ffmpeg_video_codec config to take an optional preferred_codec option.
It should not affect existing motion users.
More discussions in issue #471.

Extend ffmpeg_video_codec config to take optional preferred_codec

---

ffmpeg.c

h264_omx encoder does not take CRF option. Video quality can only be set via bit rate option.

Tune h264_omx encode video quality

---

mmalcam.c

This enhancement allows consumption of frames where resolution is not conforming to RPi firmware requirements, namely that width is a multiple of 32 and height is multiple of 16.
Currently, for such resolutions, MMAL will return a larger buffer that contains a padded frame. mmal_next will fail to process those due to unexpected size.
One way to fix those cases is to utilize MMAL_PARAMETER_NO_IMAGE_PADDING parameter that will trigger an optimized code on GPU to remove padding. One caveat is that removal is done as a second pass on provided buffer which has to accommodate initial padded image.

Handle padded MMAL frames

---

ffmpeg.c

We should not be messing with the keyframe flag in the encoded packet because encoders are likely to be buffered and even asynchronous. This PR removes setting of keyframe flag in the encoded packet.
This is a prerequisite for:
- decoupling `avcodec_receive_packet` and `avcodec_send_frame`.
- codec draining.

do not force packet keyframe

---

conf.c
conf.h
motion.1
motion.c
motion.h
motion_guide.html

Basing off the discussion in #509 (@Mr-Dave's comment - point 2 to be exact), this PR adds a runtime argument to dump the config options to the log(file). This seemed better than another log level as it needs explicit enabling and not accidental setting in the config.  
I based the sensitive information to redact off that discussion/the [Privacy Wiki](https://github.com/Motion-Project/motion/wiki/Privacy) entry, except for any of the script calls. I'm not sure the config would show sensitive information for these parameters.

Add a runtime argument to dump config options

---

conf.c

While testing in regards to issue #515, I found that writing the config kept causing a crash. I traced it down to the correction by @Mr-DaveDev of my improper `val = ...` method.  
Using a separate buffer for this should be safer than my initial reuse of the other, freed buffer.

Bugfix: config write causes crash

---

stream.c
webhttpd.c

This PR adds the requested functionality from #348.
- Add a log line including client IP to failed auth attempts in both stream and webcontrol.
- Add client IP to the generic webcontrol 'read request' log line.
Successfully tested on both stream and webcontrol with:
I don't have IPv6 within my LAN. I could probably spin up a temp VPS with v6 to test this at some point; unless someone else can test this on their current (dev) setup.
My C is a little rusty and I haven't dealt with sockets much before. Any suggestions are welcome.
_~~This will conflict with #428 (log macro)~~ (rebased and resolved)_

WIP: Log client IP (stream, webcontrol) where useful

---

Makefile.in

Fix `Makefile.in` so that it doesn't require build tree to be the same as the source tree.

autoconf: allow out-of-tree builds.

---

conf.c
conf.h
motion-dist.conf.in
motion.1
motion.c
motion.h
motion_guide.html
webhttpd.c

Implement a new configuration option which allows users to specify the type of parameters which can be accessed via the webcontrol page.  The new option permits levels 0(none) to 3(restricted) with a default of none.  This option is to enhance the security associated with the application for users that may expose the webcontrol port publicly.

Limit parameters available on webcontrol

---

netcam.c

When user specifies a URL that can not be parsed, report it as invalid instead of crashing.
Closes #572

Report invalid URLs

---

picture.c

In order to bring WEBP closer to parity with JPEG, I have implemented missing EXIF metadata handling.
The existing JPEG code was refactored so that it could be shared with both (and also for future file types).
The changes are non-intrusive and have been checked for memory leaks with valgrind.

EXIF for WEBP

---

CHANGELOG
CONTRIBUTING.md
ISSUE_TEMPLATE.md
README.md
conf.c
motion_build.html
motion_config.html
motion_guide.html

1.  Change from htmlpreview to rawgit.
2.  In guide have top menu always point to home page.
3.  Include the home page in the usage notice.
4.  Reference home page guide as preferred default
5.  Update changelog with revisions since 4.1.1

Guide Update

---

motion_build.html

- need to install automake package to get autoreconf command
- need to install postgresql package to get libpq-fe.h file
- Homebrew developers explicitly recommend against running 'sudo brew' as documented here... https://docs.brew.sh/FAQ.html

Update Mac build instructions

---

conf.c
conf.h
motion.1
motion.c
motion_config.html
stream.c
stream.h

I recently wanted to make requests to motion from a web client served from a different computer. This doesn't work because motion's response headers don't support cross-origin requests. My changes add a config parameter to motion, stream_cors_header, that inserts an Access-Control-Allow-Origin line into the response header.
The only concern I have with my addition is that I use a static buffer to store the header. stream_cors_header takes a string argument, and if it's too long I log the issue and prevent us from overflowing the buffer. If this isn't a good enough solution, I'd love feedback on how to improve it.

Cross origin resource sharing (CORS) config parameter.

---

conf.c
motion-dist.conf.in

1) `text_double` wasn't replaced by `text_scale` in the default config file
2) Copying the bool of `text_double` into `text_scale` resulted in either a 0 (no text) or 1 (no upscaling) which are both unintended results. We need to translate this bool into a 1 or 2 for the intended result.  
There might be a way to just +1 the final value here, but I didn't try going down that road (time limitations).
3) `copy_vid_ctrl` was being called on all deprecated params due to the `if` statements all being inverse of intended. This broke other deprecated params trying to copy forward (thread->camera for example).
4) `power_line_frequency` set to 0 would be skipped, but 0 is a legit value to copy forward as -1 is the default.

Fix some config issues in recent commits

---

jpegutils.c
jpegutils.h

This fixes undefined behavior concerning use of setjmp/longjmp in jpegutils.c and also removes redundant error checking that was introduced recently.

Setjmp fixes for jpegutils.c

---

ffmpeg.c

This fixes some build issues with FFmpeg 4.0. This version of FFmpeg has not yet been released, but should be shortly (ie within a few weeks).

Fix build errors with FFmpeg 4.0

---

ffmpeg.c
motion.c
netcam_rtsp.c

1.  Revert to just capturing time directly rather than in a routine.
2.  Check for null format context pointer before writing trailer.
3.  Terminate movie when lost connection.
4.  Clean up context when failed resize.
5.  Unlock mutex on failed first image.
6.  Fix memory leak when recovering from watchdog timeout.

Watchdog and RTSP time

---

webu.c

1.  Correct parameter values when using multiple cameras.  Closes #691 
2.  Clear configuration boxes when a menu action is performed.
3.  Show actual webcontrol_parm value in header for clarity to user.

Web Interface Revisions

---

mmalcam.c

Warn users that use of high frame rates could impact exposure of images.  Closes #679

Warn high framerates on mmal cams

---

conf.c
conf.h
motion.c

In commit da556d7 (store the value of 'camera_dir'), a memory leak
was introduced due to not freeing this memory in context_destroy().
I followed the advice in PR #639 to correct this.
Valgrind was used to find this leak and test for successful fixing.
Config included a 'camera_dir' with two camera config files.
Command ran: valgrind --leak-check=full ./bin/motion -n
Before:
HEAP SUMMARY:
in use at exit: 91,538 bytes in 13 blocks
total heap usage: 4,227 allocs, 4,214 frees, 20,448,321 bytes allocated
126 bytes in 3 blocks are definitely lost in loss record 8 of 11
at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
by 0x406A6D: mymalloc (motion.c:3401)
by 0x40D0CF: mystrdup (conf.c:2687)
by 0x40D30C: mystrcpy (conf.c:2664)
by 0x40D30C: copy_string (conf.c:2470) …

Fix memory leak from read_camera_dir()

---

webu.c

* `webu_text_list`: (for http://addr:port/thread/config/list in text mode) was printing the config values of thread 0 only. This adds the thread number verification and uses the requested thread if proper.
* `webu-parseurl`: found a segfault possibility by requesting a negative thread, may be limited to config lookups but a negative thread is invalid regardless. This adds a check and return on negative value given.
@Mr-Dave this shouldn't conflict with your current work on the text webu, but I'm not sure what all you're changing there.

Fix possible crash and config listing in webu

---

po/fr.po

The escaped apostrophe caused the following error when running `make`.
```
Performing the conversion of .po to .mo files
./po/fr.po:22:11: invalid control sequence
msgfmt: found 1 fatal error
```

remove incorrect escaping

---

webu.c

> When using the single 'motion.conf' file for a single camera setup, the webu actions are skipping over the only thread due to assuming that thread '0' is just motion and all cameras are subsequent.
> This leaves the webu actions useless to the default single camera, single config setup.
> 
> Fix this by checking that more than one camera thread exists to use the thread loop, using the given thread number ('0') otherwise.
Since `cam_threads` is equal to the number of total threads, we can safely check for it being greater than `1` to know which logic path is required.  
The other areas within `webu.c` utilize for loops with a separate if statement taking care of `indx` starting at `0 or 1`.
Quickly tested with `curl -v http://IP:Port/0/action/snapshot` to three config scenarios and got …

Fix webu_process_action for a default single camera config

---

motion_config.html

The default setting for 'output_pictures' option was changed
from 'on' to 'off', but the docs had not been updated.
The commit that changed the default can be seen here:
https://github.com/Motion-Project/motion/commit/ec9a5f993dbc131b58142515ededbd090c497049#diff-bedf08e0ecf6012344e7d35a645072e4L256
This change brings the docs into agreement with the new default.

update to reflect correct 'output_pictures' default

---

motion.c
motion.h
track.c

1.  Maintain a aggregate count of moves
2.  Send aggregate counts as negative when invoking center.

Generic Tracking

---

configure.ac

Static build with webp fails because webp is put before webpmux.
Fixes:
- http://autobuild.buildroot.org/results/4d4e72808300ba1ff79ca794930112b554eb2533
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

fix static linking with webp

---

webu.c

webu_hostname currently incorrectly parses IPv6 [] style IP addresses in hostnames because it misinterprets the colons within them as the port delimiting colon.

Fix webu_hostname to handle IPv6 [] colons

---

ffmpeg.c

Do video bitrate calculation using int64_t to prevent overflow.

ffmpeg: do bitrate calculation in 64 bits to prevent overflow

---

motion_config.html

Because it's actually a colon.

Avoid using word semicolon to refer to :

---

motion_config.html

The former `minimum_gap` option has been replaced by `minimum_frame_time`, if I'm not mistaking. This PR simply updates the guide to reflect this change.

Guide: replace minimum_gap with minimum_frame_time

---

event.c
motion.h

It will contain the full command line of extpipe
The problem was that this command line was only stored in a temp buffer
upon creation of the pipe. So it was not possible to write full command
line into log if pipe fails to put a frame

Add new variable to the context structure: extpipecmdline

---

event.c

Should have been FTYPE_IMAGE_SNAPSHOT instead of a generic FTYPE_IMAGE
Reported here: https://github.com/Motion-Project/motion/issues/980

Incorrect file type specified when saving snapshots

---

jpegutils.c
jpegutils.h
picture.c
picture.h

This is a prototype of the fix for https://github.com/Motion-Project/motion/issues/605
1. Reduced redundant code. put_jpeg_yuv420p_file will now call put_jpeg_yuv420p_memory to create a buffer with jpeg data, and then write the data into a file using fwrite function
2. Added jpeg error handler by copying code from jpegutil.c
3. Same changes done for put_jpeg_grey_*
@Mr-Dave, if you approve my approach then I will polish the changes and finalize this PR

jpeg code cleanup

---

configure.ac
event.c
motion.c
motion.h
track.c
video_v4l2.c

and check for defined(BSD) instead of defined(__FreeBSD__).
This makes webcams work on OpenBSD.
Resolves #904

Include sys/videoio.h as an alternative to linux/videodev2.h

---

video_v4l2.c

calling `v4l2_pixfmt_select()` resets device frame rate to default. Added `v4l2_fps_set()` after that to fix.
See discussion on bug at: [https://github.com/Motion-Project/motion/issues/923](https://github.com/Motion-Project/motion/issues/923)

v4l2_fps_set added to set device framerate

---

ffmpeg.c
ffmpeg.h

This PR adds support for h264_v4l2m2m hardware accelerated encoder. This encoder expects the input image to be in NV21 format stored in multi-planar buffers `ffmpeg->picture->buf[n]`.
I have only tested this on Odroid XU4 running Armbian kernel 4.14.127-odroidxu4, ffmpeg version 4.1.4, but I want to get this PR out early for code review and feedback from you guys.

Support h264_v4l2m2m video encoder

---

motion.c

Movies produced via emulate motion should be consistent with movies produced via normal motion detection, i.e. static images are not encoded into movie during "motion gap".

emulate motion produces movies with no pause during "motion gap"

---

ffmpeg.c

ffmpeg no longer force enable zerocopy on RPi builds. See http://ffmpeg.org/pipermail/ffmpeg-devel/2019-August/248784.html and https://trac.ffmpeg.org/ticket/6586
We can now disable zerocopy via AVOption.

OMX: disable zerocopy via AVOption

---

raspicam/README.txt
raspicam/RaspiCLI.c
raspicam/RaspiCamControl.c
raspicam/RaspiCamControl.h

Update raspicam files with latest from https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps/raspicam. These are needed for motion to recognize the new instructions when parsed as `mmalcam_control_params -command value`. Upgrading these files should not influence the way motion works in any way.
- `RaspiCamControl.c`: includes `mmal_status_to_int` function defined in the newer helper module "RaspiHelpers.h". This is not necessary for motion, so its inclusion is removed.
- `RaspiCamControl.h`: exact copy from userland
- `RaspiCLI.c`: exact copy from userland;
- `README.txt`: document changes to `RaspiCamControl.c`
@Mr-DaveDev, I did my best to document the change. If you're not happy with it I'll try something else. Cheers!

Update mmal raspicam

---

configure.ac

Buildroot requires the use of the `--no-as-needed` for some libs.  This re-implements the previous configure.ac libs specification for mmal allowing for mmal on Buildroot.

MMAL libs 

---

src/mmalcam.c

Compiling latest a22b787 without NLS in motioneyeos gives this error:
```
mmalcam.c: In function 'send_pooled_buffers_to_port':
mmalcam.c:228:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
for (int i = 0; i < num; i++) {
^
mmalcam.c:228:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
```
I did a quick search in the motion repo and this is the only instance, therefore makes send to change it here instead of adding one of the flags.

fix 'for' loop initial declaration in mmalcam.c

---

src/webu.c

Allow for embedded `&` via webcontrol
closes #1014

Revise webcontrol parsing

---

src/ffmpeg.c

The first packet that comes out of `h264_v4l2m2m` video encoder only contains NAL unit. There is no frame inside the packet. Motion currently detects this NAL packet and stores it away, but writes the NAL packet (to file) as the first frame anyway (PTS zero). When we get the first real encoded frame, motion writes the frame to file with PTS zero again, which causes playback problem in some players.
`ffprobe` sometimes gives a warning on such files, like so:
>st: 0 edit list: 1 Missing key frame while searching for timestamp: 0 
no frame
This PR stops motion from writing the NAL packet to file.

ffmpeg: do not encode NAL as the first video frame

---

src/netcam_http.c
src/stream.c

Removed _(""). GCC considers that to not be a proper format string
and does not bother checking it.
Replaced several static const chars with defines. GCC cannot check
const char * as it is a variable, not a constant expression. C
unfortunately does not support constexpr.
Discovered with -Wformat=2.

Fix format warnings

---

doc/motion_build.html

Added:
PowerTools repo which is needed to install libmicrohttpd-devel
MariaDB
PostgreSQL
WebP
Tested on CentOS 8

Updated CentOS 8 build instructions

---

src/conf.c

Updated copyright to 2020

---

src/webu_stream.c

Semicolon is used to separate extra parameters of the type. Since we do not provide any parameters, the semicolon is not needed and confusing for some parsers
Resolves: https://github.com/Motion-Project/motion/issues/1171

Removed semicolon in the Content-type value

---

src/motion.c

When `picture_output` is `first`, Motion should save first frame at start of motion and trigger an event `on_picture_save`.
Fixes #1059

Add saving first frame at motion start

---

src/draw.c

Line length was calculated from start of text instead of start of current line

Fixed longest line calculation that caused unneeded scaling of multiline text

---

.travis.yml
src/webu.c

Use MHD functions for url decoding

---

doc/motion_config.html
man/motion.1
src/conf.c
src/conf.h
src/mmalcam.c
src/motion.c
src/motion.h
src/netcam.c
src/netcam.h
src/netcam_http.c
src/netcam_rtsp.c
src/netcam_rtsp.h
src/video_bktr.c
src/video_common.c
src/video_common.h
src/video_v4l2.c
src/webu.c

- Add `netcam_params` and `netcam_high_params` options.
- Allow user specification of any additional options to netcams.
- Implement a standard set of routines for parsing parameters provided for both video devices and netcams.
- Revise option names for consistency
- `vid_control_params` => `video_params`
- `mmalcam_control_params` => `mmalcam_params`
- `videodevice` => `video_device`
- `tunerdevice` => `tuner_device`
- `netcam_highres` => `netcam_high_url`
- Conversion to use `video_params` for the following:
- `v4l2_palette` => `video_params` option of `palette`
- `input` => `video_params` option of `input`
- `frequency` => `video_params` option of `frequency`
- `norm` => `video_params` option of `norm` 
- Conversion to use `netcam_params` for the following:
- `netcam_rate` => …

Add netcam_params

---

src/netcam_rtsp.c

This change add support for Nvidia Cuda HW decode acceleration for RTSP stream.
Set netcam_decoder=cuda to enable Cuda HW acceleration
Signed-off-by: Khoa Hoang <admin@khoahoang.com>

netcam_rtsp: add support for Nvidia Cuda HW decode acceleration

---

src/webu_stream.c

This change is to correctly send back the right Content-length header for getting the current static JPG (/current).
The current code assumes that libmicrohttpd will allow overriding the header later in the process, but it does not validate that it actually accepted the override. According to libmicrohttpd documentation - Content-length is not allowed to be overriden on earlier version and in the most recent version it requires setting up and override flag to do so. However, the code structure around getting the static image is to get the image first, then setup the response element. Therefor, we already know the content-length value BEFORE we start working on the response and just use it directly.
Before the change:
% curl -vvv -m 10 -o temp.jpg http://192.168.1.45:8082/current
% Total …

Corrected value for Content-type when getting current static JPG

---

src/event.c
src/event.h
src/motion.c
src/motion.h

Resolves: https://github.com/Motion-Project/motion/issues/1337
`max_movie_time` incorrectly triggered end of the whole event, while it only supposed to flush the current movie and start recording a new file.
This PR resolves this inconsistency by introducing a new contex timestamp of the movie recording start. As soon as current movie length exceeds the config value a new event will be triggered: `EVENT_MAX_MOVIE` which will close currently recording files and start a new one.
If the `event_gap` is longer than `max_movie_time` user should expect empty movie files to be created as there will be no motion frames to put in.
Examples of running the new code:
extpipe, gap 30, max movie 10:
```
12:07:44 motion[219941]: [1:ml1] [INF] [EVT] event_new_video: Source FPS 10
12:07:44 motion[219941]: …
```

Fix for movie_max_time handling

---

doc/motion_build.html

This was missing on a default MacOSX 10.15.7 and the default brew install

[doc] Added automake dependency install for MacOSX

---

doc/motion_config.html
man/motion.1
src/conf.c
src/conf.h
src/motion.c
src/motion.h
src/netcam.c
src/netcam_rtsp.c
src/util.c
src/util.h
src/video_common.c
src/webu.c
src/webu_stream.c

Adjust the parse routines to allow for both quoted names and quoted values.
Transition `webcontrol_cors_header` to `webcontrol_header_params`
Transition `stream_cors_header` to `stream_header_parms`
Closes #1330

User Specified Webcontrol and Stream Headers

---

CONTRIBUTING.md

The "freenode" channel is essentially no more after the latest network changes resulted in two to three re-registered regulars idling, down from half a dozen or more throughout the changes and the network user base is also down considerably. If you want to see more about what happened just check out the "freenode" website and article archive/history.
As most of the regular users have already migrated to Libera Chat for many other channels, we've also started an unofficial #motion there. We should now call this the official channel. Other options would be another network or remove any IRC channel references altogether.
I can update the website IRC link as well, if this is accepted.

Update the IRC link.

---

doc/motion_config.html

Browsers may limit the number of simultaneous streams. The value of
maximum persistent connections needs to be adjusted to be greater than
the number of camera streams.

Add doc about number of simultaneous streams

---

po/pt.po
src/motion.c

and remove SIGSEGV, which is not registered
context: I was experiencing an issue where motion would terminate for no apparent reason. Looking at logs, I didn't see any error, just a normal motion graceful shutdown. After a day of investigation, I found that systemd was terminating motion due to a mis-configuration in the systemd unit. Having a log saying that motion received a signal, as implemented by this pull request, would have saved me a good few hours of debugging the problem :smiling_face_with_tear: 
PS: I see gettext .po files are being used for translation, but I'm not familiar with the gettext workflow. If a translation strings needs to be added please let me know how :)

log signals that trigger end of process

---

doc/motion_config.html

Hi,
I found the documentation's reference to `/dev/video0` in conjunction with the libcamerify wrapper a bit confusing in a multi-camera setup. IMO, not knowing libcamera properly, the wording implies that this ld_so wrapper hijacks any calls to the specifically to the `/dev/video0` path (maybe funneling them to some proprietary Pi driver or so), regardless of what device is actually registered at `/dev/video0`.  (If this were true, it would make things fairly difficult if Motion had to access both the real /dev/video0 and a wrapped one).
Only after reading your discussion at https://github.com/Motion-Project/motion/issues/1434  and the docs at https://libcamera.org/docs.html#v4l2-compatibility-layer it became apparent that the wrapper is actually transparently facilitating access to the …

Update docs with details on using libcamerify and multiple cameras on Raspberry Pi

---

Makefile.am
configure.ac
man/Makefile.am
po/de.po
po/fi.po
src/Makefile.am

**Autotools: fix `make distcheck`**
* use correct `dist_` specifiers for including files in tarball
* do not override `docdir`, since this is a user variable
* include headers in tarball
**po: fix gettext 0.22 format specifier**
Bug: https://bugs.gentoo.org/908965
Bug: https://savannah.gnu.org/bugs/index.php?64334#comment1

Gettext 0.22
