Motion-Project/motion

- conf.c
Typo fix. ERR was mentioned twice, while it should have been INF
> Typo fix. ERR was mentioned twice, while it should have been INF

- event.c
- event.h
- netcam_ftp.c
This pull includes:
https://github.com/mterzo/motion/commit/2dbff19b9dc1a6505e1a279bc210d44259bd789d (was unable to cherry-pick this one, so recommitted and credited the author)
https://github.com/mterzo/motion/commit/af270f4bb4c4ffdba7307d150537682accff039f
> Some minor changes

- conf.c
- conf.h
- configure.ac
- motion-dist.conf.in
- motion.c
- motion.h
sqlite3-busy-timeout feature to allow a wait time when database is locked.
Configure looks in the motion source for the sqlite3 amalgamation  (sqlite3.c file) and uses this
if not found the shared library is used.  Note: both the sqlite3.h and sqlite3.c files need to exist.
> Sqlite3 changes

- CHANGELOG
- CREDITS
- alg.c
- conf.c
- conf.h
- jpegutils.c
- motion.c
- motion.h
- netcam_ftp.c
- video.h
- video2.c
- video_common.c
- webhttpd.c
Here's a new pull request after rebasing and fixing up the merge issues with the Mr-Dave master branch.  I'll be closing the previous pull request.  Let me know how it goes, thanks for working on a new release.
Here are some important multithreaded race condition fixes, both startup and exit. I have a flaky USB hub to thank for frequently running into some untested code. On the feature side there's now a way to specify the power_line_frequency (important for some USB webcams), add a format width Y%3Kx%3LXY so the text doesn't jump around, the pixels changed will give a value even when under the threshold (previously there was no idea how close you were, it was either over the threshold or 0), added a new option ffmpeg_duplicate_frames to let the user decide if frames should be duplicated …
> crash fixes, , power line feature, width specifier, ffmpeg_duplicate_frames option

- configure.ac
Works for me + already tested by another user as per comments on  https://github.com/Motion-Project/motion/issues/104
> Fix for gcc crashing during configure / unable to build on raspberry pi 3

- webhttpd.c
We currently rely on gethostname() to generate the links from the web
control homepage to the camera streams - unfortunately if DNS isn't
set up well the hostname won't be one the web browser can resolve
(often the case on raspberry pi's, where the hostname is set to
"raspberrypi" by default and users access them via IP address).
To cater for these situations we look at the "Host:" header in the
HTTP headers that came from the browser (which indicate which host the
browser has been asked to connect to) and use that to generate the
hostname to use in the links.
If there's no Host: header (unlikely these days) we default back to
the old behaviour.
> Fix cases where gethostname() returns a name that doesn't work for client

- configure.ac
- motion.c
- motion_guide.html
- picture.c
Small change to the log level and added memory clean up for historic problem of the memory not being freed.
> Mask resize

- conf.c
- conf.h
- motion-dist.conf.in
> Camera configuration directory

- .gitignore
- conf.c
- conf.h
- ffmpeg.c
A couple of small fixes for various recent changes.
> Small fixes for recent changes

- netcam.c
In #197, we made the server part IPv6 compatible. The netcam client part, however, does not yet support IPv6. This PR makes the netcam part IPv6 compatible.
Unfortunately, the netcam_ftp code is still IPv4 only. It is harder to fix that, because it uses legacy, IPv4-only `gethostbyname` function. It would require more, potentially breaking changes, and I don't have a FTP camera to test it. I don't trust myself enough to change it without testing.
> Update netcam code to be IPv6 compatible

- motion.1
There are two commits in this pull request.  The first commit only cleans up trailing white space while the second on has the actual changes to the text to reflect the new configuration options.
> Manual update

- CHANGELOG
- motion_guide.html
Update to the motion_guide as well as the CHANGELOG
> Motion Guide Update

- ffmpeg.c
- ffmpeg.h
- logger.c
- motion.c
- netcam.c
- netcam.h
- netcam_rtsp.c
- netcam_rtsp.h
- stream.c
I've been running this set of commits for a number of days on my install now without any crashes, so I think it's finally good.
I recommend reviewing by looking at the diffs for each commit, as it'll make more sense then (ie. try to avoid looking at the overall diffs). It's quite a big set of changes, but I think any intermediate steps actually increase the number of crashes so I wouldn't want to merge anything other than the whole patch set. Each commit is quite small and makes sense on it's own though.
> Fixes for various threading related crashes with rtsp netcams

- conf.c
updates to conf.c to match motion-dist.conf etc
> updates to conf.c

- Makefile.in
- commit-version.sh
- git-commit-version.sh
- version.sh
Incorporates @slokhorst fixes and includes some additional changes to eliminate obsolete scripts, change to use printf instead of echo and defaults to +gitUNKNOWN when git isn't installed.
> Version fix

- motion.c
- motion_guide.html
- video_common.c
Closes #245 - Comment within comment warning
Closes #249 - Crash when too many filler frames
Closes #251 - Simple instruction in guide for installing a deb
> Small fixes

- track.c
> Fix track.c with V4L2

- webhttpd.c
> fix raw detection paused/resume response

- alg.c
- conf.c
- configure.ac
- draw.c
- ffmpeg.c
- jpegutils.c
- mmalcam.c
- netcam.c
- netcam.h
- netcam_ftp.c
- netcam_rtsp.c
- netcam_wget.c
- netcam_wget.h
- picture.c
- picture.h
- rotate.h
- stream.h
- video_common.h
- video_v4l2.h
- webhttpd.c
Remove trailing whitespace and convert tabs to four spaces.
No code changes.
> Whitespace and Tab cleanup

- configure.ac
- motion.h
- motion_guide.html
Update the autotools to use packaged applications/locations and remove the obsolete options.
> Autotool Rewrite

- motion.c
Loosen the names permitted for videodevice
Closes #331
> Camera Type

- motion.h
> FreeBSD instead of BSD for pthread_np.h

- conf.c
- conf.h
- event.c
- motion.1
- motion.c
- motion.h
- motion_guide.html
- picture.c
This PR incorporates PR #127 and includes a additional commit to resolve a few issues.  @hyperbolic2346, this commit squashes the individual commits of your branch into one with you as the author and Mr-DaveDev as the committor.  Please indicate whether this is ok.
Closes #127
> SQL Event ID

- logger.c
- logger.h
- motion.c
- netcam_rtsp.c
- netcam_rtsp.h
- video_v4l2.c
Various changes here to the logging subsystem. In a nutshell:
* Fix Valgrind-reported leak of syslog file descriptor
* Don't put RTSP URL passwords into the log
* Minor log-message touchups
> Logging fixes

- netcam.c
- netcam_rtsp.c
> Fix RTSP-related breakage

- conf.c
- conf.h
- mmalcam.c
- motion-dist.conf.in
- motion.h
- motion_guide.html
- netcam_jpeg.c
- netcam_rtsp.c
- rotate.c
- video_bktr.c
- video_v4l2.c
Addresses issue:
https://github.com/Motion-Project/motion/issues/325
> Image Flip

- netcam_rtsp.c
Experimental fix for #394 (needs testing)
> Allow invalid RTSP packets for Wansview K1 support (#394)

- motion_guide.html
> Fixes for stream_port documentation

- conf.c
Updated one log message with typo
> Log message typo

- mmalcam.c
- netcam.c
Changed informational messages from ALR to NTC
One error message text updated
> Changed informational messages from ALR to NTC

- configure.ac
Resolves: https://github.com/Motion-Project/motion/issues/427
> Replaced "AC_LINK_IFELSE" with "AC_COMPILE_IFELSE"

- alg.c
- conf.c
- event.c
- ffmpeg.c
- jpegutils.c
- logger.h
- mmalcam.c
- motion.c
- netcam.c
- netcam_ftp.c
- netcam_jpeg.c
- netcam_rtsp.c
- picture.c
- rotate.c
- stream.c
- track.c
- video_bktr.c
- video_common.c
- video_loopback.c
- video_v4l2.c
- webhttpd.c
Changed MOTION_LOG macro and removed "%s:" from the format string
Function name will be now auto added
> Changed MOTION_LOG macro

- event.c
Replace dummy file creation with access() function
> Extpipe path write access check refactor

- configure.ac
Fix for issue https://github.com/Motion-Project/motion/issues/424
> Made missing libjpeg-dev fatal configure error

- configure.ac
- motion.h
1.  Revised the MYSQL/PGSQL to search directories
2.  Revised the MYSQL/PGSQL to use the package config files if available.
3.  Revised the CPU options to honor the --without-optimizecpu option.
4.  Revised the include for MYSQL/PGSQL to conform with search and package results.
> Autotool Update

- motion.c
> Reset stream port when unable to open

- motion_guide.html
Had to compile motion for CentOS 7 and could not find a list of necessary packages. After some google'ing this is what I came up with. Compiled without errors and seems to work as well. The webcam I ordered is in the mail, so I couldn't test it yet.
> added list of packages for CentOS 7 to motion_guide.html

- ffmpeg.c
PTS value needs to be set correctly before sending the frame to the encoder. Reason being the encoder buffering up frames internally for various reasons (optimizations, etc), and eventually output encoded packet(s) at a later time. This "later time" is entirely dependent on encoder implementation, and may very well be variable delay as well. Therefore we have to timestamp (set PTS) the frames before they are sent to the encoder.
This change is also the prerequisite for the below bug fixes:
- Draining of codec before file is closed to prevent recorded video being cut short, as reported as issue #492. When draining codec, it is impossible to timestamp (set PTS) the encoded packets correctly.
- Decouple `avcodec_receive_packet` and `avcodec_send_frame` as intended by ffmpeg API. An encoder …
> set PTS value before encoding

- conf.c
- conf.h
- ffmpeg.c
- logger.c
- motion.1
- motion.c
- motion_guide.html
- netcam.c
- netcam_rtsp.c
- stream.c
- video_v4l2.c
- video_v4l2.h
1.  Validation of V4l2 Parameters(closes #494, closes #493, closes #456)
2.  Log IP on MD5 Authentication Failures
3.  Print configuration parameters to Log at INF level.(closes #509)
4.  Add flood control to log output(closes #282 )
5.  Add RTMP Protocol (closes #401)
6.  Remove error message on buffered packet (closes #457 )
> Logging, V4l2, Flood Control, RTMP Issues

- conf.c
- conf.h
- event.c
- motion-dist.conf.in
- motion.1
- motion.c
- motion_guide.html
1.  Revise the configuration options to have some of the timelapse options use distinct configuration values.
Closes #43
> Separate Timelapse Options

- .travis.yml
- conf.c
- ffmpeg.c
- motion.c
- motion.h
- netcam_ftp.c
- video_bktr.c
- video_v4l2.c
1.  Resolve new compiler warnings for 17.10 and BSD
2.  Update travis for 17.10
3.  Update copyright date
> Compiler Warnings

- version.sh
> Update version script for old distros

- jpegutils.c
> Add error checking on jpeg utils

- picture.c
> Fix saving of pictures with highres

- .travis.yml
- configure.ac
- logger.c
- motion.c
- motion.h
- stream.c
1.  Resolve the determination of the pthread_getname/pthread_setname
2.  Resolve the determination of the XSI strerror_r
3.  Add testing for musl via the Alpine docker image
Closes #550 
Closes #549
> Revision to resolve musl builds

- event.c
- ffmpeg.c
- ffmpeg.h
- motion.c
- motion.h
- motion_config.html
- netcam_rtsp.c
- netcam_rtsp.h
Using the concept/method from @iskunk branch, implement experimental version of pass-through recording of movies for wider testing.  
PR will close #124
> Pass Through Recording for RTSP Cameras

- netcam_rtsp.c
> Revise message for udp transport

- netcam.c
> Permit underscores in URLs

- logger.c
- motion.c
> Initialize the thread at start of main

- motion.c
> Capture first images for non-v4l2 devices

- netcam_rtsp.c
- video_v4l2.c
- video_v4l2.h
> Validate parms for v4l2 via netcam

- webhttpd.c
- webhttpd.h
Update the links listed on the web control page to reference the project documentation.
Print notification on web control page of the parameters included (webcontrol_parms)
> Update Web Control with Project site

- netcam_rtsp.c
Changes for the pass through recording option
> Passthrough Revisions

- motion.c
- motion.h
Updated mystrftime_long to move gethostname out of the loop
Added version specifier
> Update to mystrftime_long to move gethostname out of the loop

- motion_config.html
Update guide for conversion specifiers.
Closes #615
> Guide Update

- event.c
- motion.c
- netcam_rtsp.c
> RTSP High resolution

- webhttpd.c
Tested fix that should solve issue #641
> Missing some double \r\n

- draw.c
- motion.c
- motion.h
> Validate text_scale

- translate.c
> Updated lithuanian translation

- webu.c
Comments updated to not confuse with java
> To avoid confusion between java and javascript

- webu.c
Opening this for tracking of what I've done so far and I'll try to post screenshots as well (for feedback).
**List of things**
> New WebUI improvements

- conf.c
- conf.h
- event.c
- motion_config.html
- picture.c
Please pull this assortment of a new sql config option and little improvements in the event handling with respect to sql queries.
Thanks, 
Sander
> Event timestamp and SQL improvements

- event.c
- netcam_http.c
- stream.c
- track.c
- video_bktr.c
- video_loopback.c
- video_v4l2.c
Fixes https://github.com/Motion-Project/motion/issues/705
> Add O_CLOEXEC flag to the open of V4L2, socket and extpipe

- conf.c
- conf.h
- logger.c
- logger.h
- motion.1
- motion_config.html
- po/da.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/it.po
- po/ja.po
- po/ko.po
- po/li.po
- po/nl.po
- po/no.po
- po/pt.po
- po/sv.po
- po/zh.po
- translate.c
- translate.h
- webu.c
Add configuration option to be able to turn off native language support.
Add additional languages.
Expand messages available for translation into po files.
> Native Language Support

- event.c
- motion.c
- motion.h
- netcam.c
- netcam.h
- netcam_rtsp.c
- netcam_rtsp.h
- webu.c
This PR includes:
1.  Breaks the activities completed in the main function into separate functions.  
2.  Adds watchdog clean up for the netcam handler threads
3.  Eliminates a `goto` in the motion_loop.
4.  Unique signal function for BSD version from 2002 removed.
> Revisions to main

- conf.c
- conf.h
- motion.1
- motion_config.html
- motion_stylesheet.css
- picture.c
Add option to provide the stream in grey.
> Add stream_grey

- po/fr.po
Hi,
I propose you my french translation, in particular for webu, as asked in issue #721 .
If it's OK for you, i will continue for others items.
> Translation fr

- netcam_http.c
> add missing return to avoid contradictory logging

- Makefile.in
Return an error on make when msgfmt fails
> Test return code for msgfmt

- ffmpeg.c
> ffmpeg 4.0 revision

- video_v4l2.c
> Check for invalid dimensions

- video_bktr.c
- video_common.c
- video_common.h
- video_v4l2.c
> Revised Pixel format

- picture.c
During revision of my code I found that this loop somehow is missing few spaces to align with the code
> Aligned whitespaces

- draw.c
- motion.c
> Edits on configuration dimensions

- picture.c
Wrong array pointer increment caused V splane to run out of array bounds
Fixes https://github.com/Motion-Project/motion/issues/768
> Fixed corrupted PPM

- motion.c
- motion.h
1.  Resolve Sqlite3 equal NULL after watchdog
2.  Consolidate database routines in motion.c into dbse_ functions.
> Database Functions

- motion.c
- motion.h
- motion_config.html
- webu.c
- webu_html.c
- webu_text.c
1.  Add eventstart/eventend as options for webcontrol api.
2.  Revise action names on webcontrol html.
3.  Revise variable name in code from makemovie to event_stop.
4.  Revise some code indentation for code-folding in IDE
> Add eventstart and eventend for webcontrol

- ffmpeg.c
Fix to keyframe interval as provided by @peterholik
> Fix ffmpeg keyframe interval

- picture.h
Has been removed with cleanup of deprecated substream code
> Obsolete function

- webu_stream.c
> fix bug in webstream rate calculations

- picture.c
Fixes https://github.com/Motion-Project/motion/issues/833
> Force null terminator when writing description string into EXIF

- motion_build.html
- motion_config.html
- netcam_rtsp.c
Closes #853 
Closes #854 
Closes #855
> v4l2 via netcam revisions

- motion.c
- webu.c
- webu_stream.c
Logging messages and small revisions to stream.
> Logging messages

- conf.c
- event.c
- motion.1
- motion.c
- motion_config.html
- picture.c
- video_common.c
- webu.c
- webu_html.c
- webu_text.c
1.  Revisions for action/quit.  Closes #898 
2.  Compiler warnings (Alpine and Cosmic) Closes #868 
3.  Guide/manual update
> Webcontrol Actions

- motion.h
> OpenBSD compile

- motion.1
In response to https://github.com/Motion-Project/motion/issues/948
> Documentation ambiguity fix

- configure.ac
- motion.service.in
> systemd unit file enhancements and cleanup

- netcam.c
> fix comment

- src/ffmpeg.c
Currently when unable to select the preferred codec, motion behaves a bit different between h264_omx and h264_v4l2m2m codec. For h264_v4l2m2m codec scenario, no recording happens because it aborts. For h264_omx, it falls back to the system default codec.
This PR makes h264_v4l2m2m fall back to system default codec as well.
We previously discussed about removing the blacklist, but I feel that blacklist is a good place to keep all the ugly ffmpeg version dependent codecs in one place. Original discussion here: https://github.com/Motion-Project/motion/pull/998#discussion_r325436456
Thoughts?
> Rework blacklist

- po/LINGUAS
- po/sk.po
> Add Slovak translations

- src/netcam.c
Allow for `netcam_url` jpeg option
Closes #939
> netcam_url jpeg  option

- src/motion.c
Revise `my_bool` type to `int`
Closes #995
> mysql my_bool value

- src/motion.c
Use configuration provided database port for mariadb / mysql
Closes #1022
> mariadb / mysql database port

- configure.ac
Revise libs used for mmal.
Closes #1034
> Revise libs for mmal

- po/da.po
- po/de.po
- po/es.po
- po/fi.po
- po/fr.po
- po/it.po
- po/ja.po
- po/ko.po
- po/li.po
- po/nl.po
- po/no.po
- po/pt.po
- po/sk.po
- po/sv.po
- po/zh.po
Add default translations using the popular online translation web site.
> Add default translations

- src/netcam.h
- src/translate.c
- src/translate.h
This changes need to fix #1106
> Fix build with GCC 10.

- src/webu.c
This additional logging proved to be helpful in one of the mail list issues
> Added stream logging

- src/motion.c
> Adjust criteria for end events

- src/conf.c
- src/motion.h
- src/video_bktr.c
- src/video_common.c
- src/video_common.h
- src/video_v4l2.c
- src/webu.c
> Adjust bktr and v4l2 params

- .travis.yml
- src/motion.c
> Image Ring Process

- src/util.h
- src/webu.c
- src/webu_stream.c
- src/webu_stream.h
> Update mhd return codes

- LICENSE
This way is more "searchable" in repos as github and helps third party resources to catalog the app.
Great program by the way :+1:
>  Create LICENSE file

- src/netcam_jpeg.c
Please could you add this to support grayscale cameras. 
Without it libjpeg fails here:
https://github.com/Motion-Project/motion/blob/dc670f5da977465241171fd01dcfc6713f49d8f2/src/netcam.c#L825
I have tested the code via motioneye with this camera module for an esp32-cam board.
https://www.aliexpress.com/item/1000005245165.html
I used this version of the esp32-cam webserver:
https://github.com/easytarget/esp32-cam-webserver
I expect the code can be optimised to just a simple memcpy.
> grayscale support for network cameras

- doc/motion_config.html
Put a note in the documentation that Motion only supports 8-bit PGM mask_file
Resolves: https://github.com/Motion-Project/motion/issues/1359
> [doc] Added a note that mask_file PGM must be 8-bit

- doc/motion_config.html
- man/motion.1
- src/netcam.c
- src/netcam_rtsp.c
- src/netcam_rtsp.h
> Remove restrictions on network camera protocols

- data/camera4-dist.conf.in
- data/motion-dist.conf.in
> Update names in sample config files

- src/util.c
> Update directory permissions

- src/netcam.c
- src/video_bktr.c
Closes #1363 
Closes #1364 
Thanks @/jenny-cheung
> Avoid potential deadlocks

- src/conf.c
- src/conf.h
- src/motion.c
> Add config parameter for pause

- src/picture.c
> Remove work-around for exif format

- src/ffmpeg.c
- src/netcam_rtsp.c
> Fix segfaults with ffmpeg / netcam

- doc/motion_config.html
- src/alg.c
- src/conf.c
- src/conf.h
- src/motion.c
- src/motion.h
- src/video_v4l2.c
> Additional Parameters

- src/netcam_rtsp.c
> Allow teardown of network cameras

- src/webu.c
Originally proposed: https://gist.github.com/Mr-Dave/876aa74d62c7b054dd2602d90403bd2a
Resolves: https://github.com/Motion-Project/motion/issues/1462
> Fix event trigger on Quit

- src/conf.c
Resolves https://github.com/Motion-Project/motion/issues/1587
> Fix for double free corruption

- configure.ac
> Include libwebp when WEBP is enabled

- src/netcam_rtsp.c
Hi, I am experimenting with motion and a device with rockchip rk3229 arm 32 soc.
In order to use hardware decoding I made this little patch that enables decoding via 'drm prime' hw acceleration.
The patch has been tested with
SOC: Rockchip 3229
OS: Armbian Bookworm
Kernel: 6.1.30
FFmpeg: 5.1.3 with v4lrequests patch (https://github.com/jernejsk/FFmpeg/tree/v4l2-request-n5.1.2)
I hope it's useful
Cheers
Michele
> netcam_rtsp: add support for DRM PRIME HW decode acceleration
